services:
  simcc-client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_BASE_PATH: ${VITE_BASE_PATH:-/}
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "7004:80"
